"""
Real Supabase / PostgreSQL Live Integration & RLS Security Verification Suite.
Runs against the actual live Supabase database zzjxprhapptjoziwdcro.
"""
import os
import uuid
import pytest
from datetime import date
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")

assert SUPABASE_URL, "SUPABASE_URL must be defined"
assert SUPABASE_SERVICE_KEY, "SUPABASE_SERVICE_KEY must be defined"
assert SUPABASE_ANON_KEY, "SUPABASE_ANON_KEY must be defined"

admin_client: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
anon_client: Client = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)


@pytest.fixture(scope="module")
def setup_test_users():
    """Create two real test users via Supabase Admin API and clean them up after tests."""
    email_a = f"audit_a_{uuid.uuid4().hex[:8]}@skillscatalyst.internal"
    email_b = f"audit_b_{uuid.uuid4().hex[:8]}@skillscatalyst.internal"
    password = "AuditSecurePassword123!#"

    # Create User A
    user_a_resp = admin_client.auth.admin.create_user({
        "email": email_a,
        "password": password,
        "email_confirm": True,
        "user_metadata": {"full_name": "Audit User A"}
    })
    user_a = user_a_resp.user
    assert user_a and user_a.id, f"Failed to create User A: {user_a_resp}"

    # Create User B
    user_b_resp = admin_client.auth.admin.create_user({
        "email": email_b,
        "password": password,
        "email_confirm": True,
        "user_metadata": {"full_name": "Audit User B"}
    })
    user_b = user_b_resp.user
    assert user_b and user_b.id, f"Failed to create User B: {user_b_resp}"

    # Authenticate as User A and User B to get session tokens using dedicated anon auth clients
    auth_a = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    session_a = auth_a.auth.sign_in_with_password({"email": email_a, "password": password})
    client_a = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    client_a.postgrest.auth(session_a.session.access_token)

    auth_b = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    session_b = auth_b.auth.sign_in_with_password({"email": email_b, "password": password})
    client_b = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    client_b.postgrest.auth(session_b.session.access_token)

    yield {
        "user_a_id": user_a.id,
        "user_b_id": user_b.id,
        "client_a": client_a,
        "client_b": client_b,
        "token_a": session_a.session.access_token,
        "token_b": session_b.session.access_token,
    }

    # Cleanup test users
    try:
        admin_client.auth.admin.delete_user(user_a.id)
    except Exception as e:
        print(f"Warning cleaning user A: {e}")
    try:
        admin_client.auth.admin.delete_user(user_b.id)
    except Exception as e:
        print(f"Warning cleaning user B: {e}")


# ==============================================================================
# 1. REAL DATABASE CRUD & SCHEMA TESTS (against live Postgres)
# ==============================================================================

def test_real_db_user_skills_crud(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    # Insert (UUID should be auto-generated by gen_random_uuid())
    res_ins = client_a.table("user_skills").insert({
        "user_id": uid,
        "skill_name": "PostgreSQL",
        "category": "Database",
        "proficiency": "Advanced"
    }).execute()

    assert len(res_ins.data) == 1
    skill = res_ins.data[0]
    skill_id = skill["id"]
    assert skill_id is not None
    # Validate it's a valid UUID
    uuid.UUID(skill_id)
    assert skill["skill_name"] == "PostgreSQL"
    assert skill["category"] == "Database"
    assert skill["proficiency"] == "Advanced"

    # Update
    res_upd = client_a.table("user_skills").update({
        "proficiency": "Expert"
    }).eq("id", skill_id).execute()
    assert len(res_upd.data) == 1
    assert res_upd.data[0]["proficiency"] == "Expert"

    # Delete
    res_del = client_a.table("user_skills").delete().eq("id", skill_id).execute()
    assert len(res_del.data) == 1

    # Verify gone
    res_check = client_a.table("user_skills").select("*").eq("id", skill_id).execute()
    assert len(res_check.data) == 0


def test_real_db_experiences_date_behavior(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    # Insert experience with valid DATE, currently_working=True, end_date=None
    res = client_a.table("experiences").insert({
        "user_id": uid,
        "company_name": "Google DeepMind",
        "role": "Research Engineer",
        "location": "London, UK",
        "work_type": "Hybrid",
        "employment_type": "Full-time",
        "start_date": "2024-03-01",
        "end_date": None,
        "currently_working": True,
        "description": "Leading agentic LLM architecture"
    }).execute()

    assert len(res.data) == 1
    exp = res.data[0]
    exp_id = exp["id"]
    uuid.UUID(exp_id)
    assert exp["start_date"] == "2024-03-01"
    assert exp["end_date"] is None
    assert exp["currently_working"] is True

    # Cleanup
    client_a.table("experiences").delete().eq("id", exp_id).execute()


def test_real_db_education_ordering_and_dates(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    # Insert two education records with different end_dates
    e1 = client_a.table("education").insert({
        "user_id": uid,
        "college": "High School",
        "degree_type": "Secondary",
        "field_of_study": "Science",
        "gpa": "9.2",
        "start_date": "2018-06-01",
        "end_date": "2020-05-01",
        "currently_studying": False
    }).execute().data[0]

    e2 = client_a.table("education").insert({
        "user_id": uid,
        "college": "Stanford University",
        "degree_type": "B.Tech",
        "field_of_study": "Computer Science",
        "gpa": "3.9",
        "start_date": "2020-09-01",
        "end_date": "2024-06-01",
        "currently_studying": False
    }).execute().data[0]

    # Query with order by end_date desc
    res = client_a.table("education").select("*").order("end_date", desc=True).execute()
    assert len(res.data) >= 2
    assert res.data[0]["college"] == "Stanford University"
    assert res.data[1]["college"] == "High School"

    # Cleanup
    client_a.table("education").delete().in_("id", [e1["id"], e2["id"]]).execute()


def test_real_db_projects_array_round_trip(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    techs = ["Next.js", "PostgreSQL", "FastAPI", "TailwindCSS"]
    res = client_a.table("projects").insert({
        "user_id": uid,
        "project_name": "SkillsCatalyst Engine",
        "description": "Enterprise career readiness platform",
        "technologies": techs,
        "start_date": "2024-01-15",
        "end_date": None,
        "github_url": "https://github.com/skillscatalyst/core",
        "live_demo_url": "https://skillscatalyst.in",
        "currently_working": True
    }).execute()

    assert len(res.data) == 1
    proj = res.data[0]
    assert proj["technologies"] == techs
    assert proj["technologies"][1] == "PostgreSQL"

    # Cleanup
    client_a.table("projects").delete().eq("id", proj["id"]).execute()


def test_real_db_career_preferences_arrays_and_academic_sync(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    roles = ["Full Stack Developer", "AI Engineer"]
    industries = ["Fintech", "HealthTech"]
    companies = ["Google", "Stripe"]
    locations = ["Remote", "Hyderabad"]
    arrangements = ["Remote", "Hybrid"]

    # Upsert career preferences
    res = client_a.table("career_preferences").upsert({
        "user_id": uid,
        "target_roles": roles,
        "preferred_industries": industries,
        "target_companies": companies,
        "preferred_locations": locations,
        "work_arrangements": arrangements
    }).execute()

    assert len(res.data) == 1
    pref = res.data[0]
    assert pref["target_roles"] == roles
    assert pref["preferred_industries"] == industries
    assert pref["target_companies"] == companies
    assert pref["preferred_locations"] == locations
    assert pref["work_arrangements"] == arrangements


def test_real_db_achievements_ordering(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    a1 = client_a.table("achievements").insert({
        "user_id": uid,
        "achievement_name": "Hackathon 2023",
        "organization": "Major League Hacking",
        "achievement_date": "2023-04-10",
        "description": "Runner up"
    }).execute().data[0]

    a2 = client_a.table("achievements").insert({
        "user_id": uid,
        "achievement_name": "Hackathon 2024",
        "organization": "Smart India Hackathon",
        "achievement_date": "2024-09-01",
        "description": "Winner"
    }).execute().data[0]

    # Query ordered by achievement_date desc
    res = client_a.table("achievements").select("*").order("achievement_date", desc=True).execute()
    assert len(res.data) >= 2
    assert res.data[0]["achievement_name"] == "Hackathon 2024"

    # Cleanup
    client_a.table("achievements").delete().in_("id", [a1["id"], a2["id"]]).execute()


# ==============================================================================
# 2. REAL TWO-USER RLS SECURITY VERIFICATION
# ==============================================================================

def test_real_rls_cross_user_isolation(setup_test_users):
    """
    CRITICAL MULTI-TENANT TEST:
    User A inserts private profile data.
    User B MUST NOT be able to read, update, or delete it.
    User B MUST NOT be able to insert data with User A's ID.
    """
    client_a = setup_test_users["client_a"]
    client_b = setup_test_users["client_b"]
    uid_a = setup_test_users["user_a_id"]
    uid_b = setup_test_users["user_b_id"]

    # 1. User A inserts a private skill
    skill_a = client_a.table("user_skills").insert({
        "user_id": uid_a,
        "skill_name": f"PrivateSkill_{uuid.uuid4().hex[:6]}",
        "category": "Secret",
        "proficiency": "Master"
    }).execute().data[0]

    # 2. User B tries to read User A's skill directly by ID
    res_b_read = client_b.table("user_skills").select("*").eq("id", skill_a["id"]).execute()
    # RLS must filter this row out: User B sees empty list
    assert len(res_b_read.data) == 0, "SECURITY BREACH: User B read User A's skill!"

    # 3. User B tries to query all skills for user_id = User A
    res_b_read_all = client_b.table("user_skills").select("*").eq("user_id", uid_a).execute()
    assert len(res_b_read_all.data) == 0, "SECURITY BREACH: User B queried User A's skills list!"

    # 4. User B tries to update User A's skill
    res_b_upd = client_b.table("user_skills").update({
        "proficiency": "Compromised"
    }).eq("id", skill_a["id"]).execute()
    assert len(res_b_upd.data) == 0, "SECURITY BREACH: User B modified User A's skill!"

    # Verify skill A remains unchanged
    skill_a_verify = client_a.table("user_skills").select("*").eq("id", skill_a["id"]).execute().data[0]
    assert skill_a_verify["proficiency"] == "Master"

    # 5. User B tries to delete User A's skill
    res_b_del = client_b.table("user_skills").delete().eq("id", skill_a["id"]).execute()
    assert len(res_b_del.data) == 0, "SECURITY BREACH: User B deleted User A's skill!"

    # 6. User B tries to insert a child record using User A's user_id (Impersonation attack)
    impersonation_failed = False
    try:
        res_b_hack = client_b.table("user_skills").insert({
            "user_id": uid_a, # Malicious payload: User B claims User A's ID
            "skill_name": "TrojanSkill",
            "category": "Attack",
            "proficiency": "Malicious"
        }).execute()
        # If no exception, check if data was actually rejected or blocked
        if len(res_b_hack.data) == 0:
            impersonation_failed = True
    except Exception as e:
        # Postgres RLS WITH CHECK policy violation raises an error
        impersonation_failed = True
        assert "policy" in str(e).lower() or "row-level security" in str(e).lower() or "new row violates" in str(e).lower()

    assert impersonation_failed, "SECURITY BREACH: User B inserted a record with User A's user_id!"

    # Cleanup
    client_a.table("user_skills").delete().eq("id", skill_a["id"]).execute()


def test_real_rls_anonymous_access_denied():
    """
    CRITICAL PERMISSION TEST:
    Anonymous requests must be completely blocked by DAC/RLS from reading private profile tables.
    """
    private_tables = [
        "user_skills", "experiences", "education",
        "projects", "certifications", "achievements", "career_preferences"
    ]
    for table in private_tables:
        blocked = False
        try:
            res = anon_client.table(table).select("*").limit(5).execute()
            # If no exception, RLS must return empty list
            if len(res.data) == 0:
                blocked = True
        except Exception as e:
            # 42501 permission denied or 401
            blocked = True
        assert blocked, f"SECURITY BREACH: Anonymous client accessed table '{table}'!"


def test_real_rls_service_role_bypass():
    """
    CRITICAL BACKEND SERVICE TEST:
    Service role key MUST be able to read and write across tables for background workers,
    coding platform scrapers, and admin tasks.
    """
    # Service role queries career_preferences
    res = admin_client.table("career_preferences").select("user_id").limit(5).execute()
    assert res.data is not None, "Service role was blocked from backend table access!"


def test_real_db_certifications_crud(setup_test_users):
    client_a = setup_test_users["client_a"]
    uid = setup_test_users["user_a_id"]

    res = client_a.table("certifications").insert({
        "user_id": uid,
        "certification_name": "AWS Certified Solutions Architect",
        "issuing_organization": "Amazon Web Services",
        "issue_date": "2024-05-15",
        "expiration_date": "2027-05-15",
        "credential_id": "AWS-SA-9999",
        "credential_url": "https://aws.amazon.com/verify/9999"
    }).execute()

    assert len(res.data) == 1
    cert = res.data[0]
    uuid.UUID(cert["id"])
    assert cert["issue_date"] == "2024-05-15"
    assert cert["expiration_date"] == "2027-05-15"

    # Cleanup
    client_a.table("certifications").delete().eq("id", cert["id"]).execute()


def test_real_db_profile_sync_trigger(setup_test_users):
    """Verify live PostgreSQL trigger trg_sync_profile_to_academic."""
    uid = setup_test_users["user_a_id"]
    new_name = f"Updated Live Name {uuid.uuid4().hex[:6]}"

    # Upsert profiles.full_name via admin_client
    admin_client.table("profiles").upsert({
        "id": uid,
        "email": "test_audit_sync@skillscatalyst.internal",
        "full_name": new_name
    }).execute()

    # Query user_academic_profile to confirm trigger copied full_name
    acad = admin_client.table("user_academic_profile").select("full_name").eq("user_id", uid).execute()
    assert len(acad.data) == 1
    assert acad.data[0]["full_name"] == new_name


def test_real_api_profile_contract_live(setup_test_users):
    """Test actual FastAPI GET and POST profile endpoints using the live Supabase database."""
    from fastapi.testclient import TestClient
    from backend.main import app
    from backend.routers.profile import get_current_user_id

    uid = setup_test_users["user_a_id"]
    client = TestClient(app)


    # Override user dependency to point to live test user A
    app.dependency_overrides[get_current_user_id] = lambda: uid
    try:
        # 1. POST /api/profile/personal
        post_res = client.post("/api/profile/personal", json={
            "full_name": "Live Integration User",
            "headline": "Full-Stack System Architect",
            "country": "India",
            "state": "Telangana",
            "city": "Hyderabad",
            "gender": "Male",
            "about": "Testing live production contracts",
            "avatar_url": "https://avatar.url/me.png"
        })
        assert post_res.status_code == 200
        assert post_res.json().get("success") is True

        # 2. POST /api/profile/career-preferences
        pref_res = client.post("/api/profile/career-preferences", json={
            "target_roles": ["Principal Architect", "Tech Lead"],
            "preferred_industries": ["Fintech", "Cloud"],
            "target_companies": ["Google", "Stripe"],
            "preferred_locations": ["Remote", "Bengaluru"],
            "work_arrangements": ["Remote"]
        })
        assert pref_res.status_code == 200
        assert pref_res.json().get("success") is True

        # 3. GET /api/profile
        get_res = client.get("/api/profile")
        assert get_res.status_code == 200
        data = get_res.json()
        assert "personal" in data
        assert data["personal"].get("full_name") == "Live Integration User"
        assert data["personal"].get("headline") == "Full-Stack System Architect"
        assert data["personal"].get("city") == "Hyderabad"
        prefs = data.get("career_preferences", {})
        assert prefs.get("target_roles") == ["Principal Architect", "Tech Lead"]
        assert prefs.get("work_arrangements") == ["Remote"]
    finally:
        app.dependency_overrides.pop(get_current_user_id, None)

